.\" miau.1 - yet another IRC-bouncer
.\" Copyright 2005  Tommi Saviranta  <wnd@iki.fi>
.TH miau 1 "May 20 2005" "miau 0.5.4"
.SH NAME
MIAU \- Yet another IRC-bouncer
.SH SYNOPSIS
.B miau [options]
.br
.B miau-check
.SH DESCRIPTION
Close your IRC-client without being disconnected from IRC.
.P
.B miau
is the actual binary and
.B miau-check
can be used with
.B cron
to make sure
.B miau
is restarted after reboot.
.SH AUTHOR
.B miau
is being written and maintained by Tommi Saviranta <wnd@iki.fi> based on the
original codebase by Sebastian Kienzl <zap@riot.org> and Lee Hardy
<lee@leeh.co.uk>. List of contributors can be found in file named AUTHORS,
included in standard distribution package.
.SH OTHER INFO
The webpage for miau is http://miau.sf.net/. Here you can find info about miau
and download the latest version.

This manual page was written for your convience, see
.B info miau
for more detailed documentation.
.SH SEE ALSO
.BR crontab (1)
